config/routes.rb
Rails.application.routes.draw do
  root "entries#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :users, only: [:edit, :update, :show]
  resources :tags, only: [:show]
  resources :entries do
    resources :comments, only: [:create]
    collection do
      get "search"
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :comments, dependent: :destroy
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :text
  end

  validates :title, length: { maximum: 50 }
  validates :text, length: { maximum: 255 }

  mount_uploader :image, ImageUploader

  def self.search(search)
    return Entry.all unless search
    Entry.where('text LIKE(?)', "%#{search}%")
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_entry, only: [:edit, :update, :show, :destroy]
  before_action :set_tags

  def index
    @entries = Entry.all.includes(:user).order("created_at DESC").page(params[:page]).per(9)
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to root_path, notice: "投稿しました"
    else
      redirect_to new_entry_path, alert: "必須項目を入力してください"
    end
  end

  def edit
  end

  def update
    @entry.update(entry_params) if @entry.user_id == current_user.id
    if @entry.update(entry_params)
      redirect_to entry_path, notice: "投稿を更新しました"
    else
      redirect_to edit_entry_path, alert: "必須項目を入力してください"
    end
  end

  def show
    @comment = Comment.new
    @comments = @entry.comments.includes(:user)
  end

  def search
    @entries = Entry.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(9)
    @keyword_count = @entries.count
    respond_to do |format|
      format.html
      format.json
    end
  end

  def destroy
    @entry.destroy  if @entry.user_id == current_user.id
    if @entry.destroy
      redirect_to root_path, notice: "削除しました"
    else
      render :show, flash[:alert] = "削除に失敗しました"
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:url, :image, :text, :title, tag_ids: []).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def set_tags
    @time = Tag.all.to_a.slice(0..4)
    @place = Tag.all.to_a.slice(5..8)
    @feeling = Tag.all.to_a.slice(9..13)
    @tag = Tag.find_by(id: params[:id])
  end
end

app/views/entries/edit.html.haml
.entryform
  .entryform__top
    .entryform__top__left-corner
    .entryform__top__right-corner

  .entryform__inner
    .entryform__inner__header
      %h2 投稿編集
    .entryform__innner__form
      = form_for @entry do |f|
        .field
          .field-label
            = f.label :タイトル
          .field-input
            = f.text_field :title, maxlength: "50", class: "js-count", autofocus: true
            .counter
              %span.show-count> 0
              \/ 50

          .field_tags
            .field-tags__title
              タグ一覧
            .field-tags__time
              = f.label :時間の目安, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(0..4), :id, :name

            .field-tags__place
              = f.label :行う場所, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(5..8), :id, :name

            .field-tags__feeling
              = f.label :気分／雰囲気, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(9..13), :id, :name

        .field
          .field-label
            = f.label :本文
          .field-input
            = f.text_area :text, maxlength: "255", class: "js-count"
            .counter
              %span.show-count> 0
              \/ 255
        .field
          .field-label
            画像選択／プレビュー（画像投稿後は差し替えのみ可能です）
          = f.label :image, class: "field-image" do
            %i.far.fa-image.fa-2x
              = f.file_field :image, class: "field-file"
          .preview-box
            .preview
              - if @entry.image.present?
                = image_tag @entry.image.url, class: "preview"
            .image-delete
              Delete

        .field
          .field-label
            = f.label :URL
          .field-input
            = f.text_field :url
        .actions
          = f.submit "Update", class: 'btn'

  .entryform__bottom
    .entryform__bottom__left-corner
    .entryform__bottom__right-corner

app/views/entries/index.html.haml
.entries
  = render partial: "shared/entries", locals: {entries: @entries}

app/views/entries/new.html.haml
.entryform
  .entryform__top
    .entryform__top__left-corner
    .entryform__top__right-corner

  .entryform__inner
    .entryform__inner__header
      %h2 新規投稿
    .entryform__innner__form
      = form_for @entry do |f|
        .field
          .field-label
            = f.label :タイトル
          .field-input
            = f.text_field :title, maxlength: "50", class: "js-count", autofocus: true
            .counter
              %span.show-count> 0
              \/ 50

          .field_tags
            .field-tags__title
              タグ一覧
            .field-tags__time
              = f.label :時間の目安, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(0..4), :id, :name

            .field-tags__place
              = f.label :行う場所, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(5..8), :id, :name

            .field-tags__feeling
              = f.label :気分／雰囲気, class: "field-tags__category"
              = f.collection_check_boxes :tag_ids, Tag.all.to_a.slice(9..13), :id, :name

        .field
          .field-label
            = f.label :本文
          .field-input
            = f.text_area :text, maxlength: "255", class: "js-count"
            .counter
              %span.show-count> 0
              \/ 255
        .field
          .field-label
            画像選択／プレビュー（画像投稿後は差し替えのみ可能です）
          = f.label :image, class: "field-image" do
            %i.far.fa-image.fa-2x
              = f.file_field :image, class: "field-file"
          .preview-box
            .preview
            .image-delete
              Delete

        .field
          .field-label
            = f.label :URL
          .field-input
            = f.text_field :url, style:"ime-mode:disabled;"
        .actions
          = f.submit "New Entry", class: 'btn'

  .entryform__bottom
    .entryform__bottom__left-corner
    .entryform__bottom__right-corner

app/views/entries/search.html.haml
.entries
  .entries__top
    .entries__top__left-corner
    .entries__top__right-corner

  .entries__latest-title
    .title-box
      %h2 キーワード検索
      %h4
        = "検索結果： #{@keyword_count} 件"

  .entries__latest-tiles
    - @entries.each do |entry|
      = link_to entry_path(entry.id), class: "tile" do
        - if entry.image.present?
          = image_tag entry.image.url, class: "tile__image"
        - else
          .tile__noimage
        .tile__title
          = entry.title
        .tile__user-name
          = entry.user.name
  = paginate(@entries)

  .entries__bottom
    .entries__bottom__left-corner
    .entries__bottom__right-corner

app/views/entries/show.html.haml
.entry
  .entry__top
    .entry__top__left-corner
    .entry__top__right-corner

  .entry__detail
    - if current_user == @entry.user
      .edit-box
        = link_to "Edit", edit_entry_path, class: "entry-edit"
        = link_to "Delete", entry_path(@entry), class: "entry-delete", method: :delete
    - if user_signed_in? && current_user != @entry.user
      %i.fas.fa-heart.fa-2x
    - if @entry.image.present?
      = image_tag @entry.image.url, class: "entry__detail__image"
    - else
      .entry__detail__noimage
    .entry__detail__title
      = @entry.title
    .entry__detail__user-name
      = link_to @entry.user.name, user_path(@entry.user_id)
    .entry__detail__text
      = @entry.text
    .entry__detail__url
      - if @entry.url?
        = raw Rinku.auto_link(simple_format(h(@entry.url)), mode=:all, link_attr='target="_blank", rel="noopener"', skip_tags=nil)
      - else
        URLはありません
    .entry__detail__tags
      タグ：
      - @entry.tags.each do |tag|
        .entry-tag
          = link_to tag.name, tag_path(tag.id)


  .entry__comments
    .entry__comments__list
      - if @comments
        - @comments.each do |comment|
          .entry__comments__list__box
            .entry__comments__list__box__text
              = comment.text
            .entry__comments__list__box__user-name
              = link_to comment.user.name, user_path(comment.user_id)

    .entry__comments__form
      - if current_user
        = form_for [@entry, @comment] do |f|
          .field-input
            = f.text_field :text, maxlength: "100", class: "js-count", placeholder: "コメントをどうぞ"
            .counter
              %span.show-count> 0
              \/ 100
          .actions
            = f.submit "Send", class: 'btn'

  .entry__bottom
    .entry__bottom__left-corner
    .entry__bottom__right-corner