config/routes.rb
Rails.application.routes.draw do
  root "entries#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :users, only: [:edit, :update, :show]
  resources :tags, only: [:show]
  resources :entries do
    resources :comments, only: [:create]
    collection do
      get "search"
    end
  end
end

app/views/shared/_entries.html.haml
.entries__top
  .entries__top__left-corner
  .entries__top__right-corner

.entries__latest-title
  %h2 最新投稿

.entries__latest-tiles
  - entries.each do |entry|
    = link_to entry_path(entry.id), class: "tile" do
      - if entry.image.present?
        = image_tag entry.image.url, class: "tile__image"
      - else
        .tile__noimage
      .tile__title
        = entry.title
      .tile__user-name
        = entry.user.name
= paginate(@entries)

.entries__bottom
  .entries__bottom__left-corner
  .entries__bottom__right-corner

app/views/shared/_footer.html.haml
.footer
  .footer__credit
    あぷりのいらすと＠いらすとやさん

app/views/shared/_side.html.haml
.side
  .side__header
    .side__header__appname
      = link_to image_tag("appname_spring.png", size: "250x193", title: "トップページ"), root_path
    .side__header__system-menu
      .side__header__system-menu__user
        - if user_signed_in?
          = link_to image_tag("current_user.png", size: "30x41", title: "ユーザー編集"), edit_user_path(current_user)
        - else
          = link_to image_tag("new_user.png", size: "30x41", title: "新規登録"), new_user_registration_path
      .side__header__system-menu__post
        - if user_signed_in?
          = link_to image_tag("users_post.png", size: "32x37", title: "新規投稿"), new_entry_path
        - else
          = link_to image_tag("current_user.png", size: "30x41", title: "ログイン"), new_user_session_path
      .side__header__system-menu__official-twitter
        = link_to image_tag("bluebird.png", size: "45x41", title: "製作者のTwitter"), "https://twitter.com/cache_cache_la", target: :_blank, rel: :noopener

  .side__box
    .side__box__keyword-search
      = form_with(url: search_entries_path, local: true, method: :get, class: "form") do |f|
        = f.text_field :keyword, placeholder: " キーワード検索", class: "search-words"
        = f.submit "", class: "search-btn"

    .side__box__tags

    .side__box__tag-list

      %ul.side__box__tag-list__time
        %b 時間の目安
        - @time.each do |tm|
          %li.tag__time
            = link_to "#{tm.name}", tag_path(tm.id)

      %ul.side__box__tag-list__place
        %b 行う場所
        - @place.each do |pl|
          %li.tag__place
            = link_to "#{pl.name}", tag_path(pl.id)

      %ul.side__box__tag-list__feeling
        %b 気分／雰囲気
        - @feeling.each do |fl|
          %li.tag__feeling
            = link_to "#{fl.name}", tag_path(fl.id)